### PR TITLE
Update admin.plugin.lua

### PR DESCRIPTION
**Pull request by TesDevelopment**

### CODE REVIEW

**Comment by stangithuboffical** [comment]
OK WHY ARE YOU MULTIPING THE TIME???

**Comment by Autist69420** [comment]
stan stop malding

**Comment by stangithuboffical** [comment]
> stan stop malding

suck my ass autist you havent been active since 10 years

**Comment by Autist69420** [comment]
> 
> 
> > stan stop malding
> 
> suck my ass autist you havent been active since 10 years

i'd rather not my good sir

**Comment by stangithuboffical** [comment]
> > > stan stop malding
> > 
> > 
> > suck my ass autist you havent been active since 10 years
> 
> i'd rather not my good sir

die i work for roblox.

**Comment by Autist69420** [comment]
> 
> 
> > > > stan stop malding
> > > 
> > > 
> > > suck my ass autist you havent been active since 10 years
> > 
> > 
> > i'd rather not my good sir
> 
> die i work for roblox.

make me die

**Comment by pozm** [comment]
code does not work. error on execution.

**Pull request closed without merging**
