### PR TITLE
Rewrote pluginManager

### PR DESCRIPTION
**Pull request by TesDevelopment**

### CODE REVIEW

**Comment by Autist69420** [comment]
lovely

**Comment by Autist69420** [comment]
hey also its spelled **declarations** not **declerations**

**Comment by TesDevelopment** [comment]
omg im an idiot lmao fixing.

**Comment by fatesc** [comment]
read https://github.com/fatesc/fates-admin/wiki/Globals#notify and see why this won't work

**Comment by pozm** [comment]
go dsf go!

**Comment by pozm** [comment]
@TesDevelopment also you used the incorrect terminology, it should be function definitions as declaring is not defining

**Comment by Autist69420** [comment]
we do a little trolling :trollface:

**Comment by TesDevelopment** [comment]
> read https://github.com/fatesc/fates-admin/wiki/Globals#notify and see why this won't work

Godamnit I wrote this with the old notify I’ll fix when I’m on my pc. Thanks for the heads up.

**Comment by NotDSF** [comment]
why am I assigned bro

**Comment by NotDSF** [comment]
also fate give me admin back

**Comment by NotDSF** [comment]
<@798262622696636450>

**Comment by Autist69420** [comment]
> 
> 
> why am I assigned bro

because you're so good a LuaU :trollface:

**Comment by TesDevelopment** [comment]
There ya go <@798262622696636450>

**Comment by NotDSF** [comment]
c

**Comment by Autist69420** [comment]
bruh

**Comment by NotDSF** [comment]
happy now?

**Comment by TesDevelopment** [comment]
> happy now?

yes

**Comment by fatesc** [comment]
don't ever try to contribute again

**Pull request merged**
